// Package packageB provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen DO NOT EDIT.
package packageB

import validation "github.com/go-ozzo/ozzo-validation/v4"

// ObjectB defines model for ObjectB.
type ObjectB struct {
	Name *string `json:"name,omitempty"`
}

// Validate perform validation on the ObjectB
func (s ObjectB) Validate() error {
	// Run validate on a struct
	return validation.ValidateStruct(
		&s,
		validation.Field(
			&s.Name,
		),
	)

}
